name: sdl-linux-test-ci
on:
  push:
    branches:
      - "main"
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: New vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          cd ./vcpkg
          git checkout 843e0ba0d8f9c9c572e45564263eedfc7745e74f
          cd ../
      # - name: Configure
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install make
      #     sudo apt-get install yasm
      #     bash .github/scripts/linux/configure.sh
      # - name: Build
      #   run: bash .github/scripts/linux/build.sh
